var RoomObj=function(){
//
	this.ip="";
//
	this.port=0;
//
	this.uploadPort=0;
//
	this.tomcatPort=0;
//
	this.roomId="";
//
	this.playerCount=0;
//
	this.count=0;
//
	this.roomType=0;
//
	this.leftTime=0;

this.write=function(bodybuff)
{
	bodybuff.putUTF(this.ip);
	bodybuff.putInt(this.port);
	bodybuff.putInt(this.uploadPort);
	bodybuff.putInt(this.tomcatPort);
	bodybuff.putUTF(this.roomId);
	bodybuff.putInt(this.playerCount);
	bodybuff.putInt(this.count);
	bodybuff.putInt(this.roomType);
	bodybuff.putInt(this.leftTime);
};
this.read=function(buffer)
{
	this.ip=buffer.readUTF();
	this.port=buffer.readInt();
	this.uploadPort=buffer.readInt();
	this.tomcatPort=buffer.readInt();
	this.roomId=buffer.readUTF();
	this.playerCount=buffer.readInt();
	this.count=buffer.readInt();
	this.roomType=buffer.readInt();
	this.leftTime=buffer.readInt();
};
this.clone=function()
{
var cloneObj={};
cloneObj.ip=this.ip;
cloneObj.port=this.port;
cloneObj.uploadPort=this.uploadPort;
cloneObj.tomcatPort=this.tomcatPort;
cloneObj.roomId=this.roomId;
cloneObj.playerCount=this.playerCount;
cloneObj.count=this.count;
cloneObj.roomType=this.roomType;
cloneObj.leftTime=this.leftTime;
cloneObj.read=this.read;
cloneObj.write=this.write;
cloneObj.clone=this.clone;
return cloneObj;
};
};
